using System.Collections.Generic;

namespace DalamudACT
{
    public class Potency
    {
        public static readonly float[] Muti = new[]
        {
            0f, //冒险者
            2.24f / 3f, //剑术师
            2.56f / 3f, //格斗家
            1.12f, //斧术师
            2.8f / 3f, //枪术师
            3.04f / 3f, //弓箭手
            1.0f, //幻术师
            1.0f, //咒术师
            0f, //刻木匠
            0f, //锻铁匠
            0f, //铸甲匠
            0f, //雕金匠
            0f, //制革匠
            0f, //裁衣匠
            0f, //炼金术士
            0f, //烹调师
            0f, //采矿工
            0f, //园艺工
            0f, //捕鱼人
            2.24f / 3f, //骑士
            2.56f / 3f, //武僧
            1.12f, //战士
            2.8f / 3f, //龙骑士
            3.04f / 3f / 1.2f, //诗人
            1f, //白魔法师
            1f, //黑魔法师 天语没算
            1.0f, //秘术师
            1f, //召唤师
            1f, //学者
            1.0f, //双剑师
            2.56f / 3f, //忍者
            0.88f / 1.2f, //机工士
            2.96f / 3f, //暗黑骑士
            1f, //占星术士
            0.88f, //武士 
            1f, //赤魔法师
            0f, //青魔法师
            2.8f / 3f, //绝枪战士
            1.04f / 1.2f, //舞者
            3.2f / 3f, //Reaper
            1f, //贤者
            2.64f / 3f, //Viper
            1f, //画家
        };

        public static readonly uint[] BaseSkill =
        {
            0, //冒险者
            7, //剑术师
            7, //格斗家
            7, //斧术师
            7, //枪术师
            7, //弓箭手
            7, //幻术师
            7, //咒术师
            0, //刻木匠
            0, //锻铁匠
            0, //铸甲匠
            0, //雕金匠
            0, //制革匠
            0, //裁衣匠
            0, //炼金术士
            0, //烹调师
            0, //采矿工
            0, //园艺工
            0, //捕鱼人
            7, //骑士
            7, //武僧
            7, //战士
            7, //龙骑士
            8, //诗人
            25859, //白魔法师 Glare III
            3577, //黑魔法师 天语没算
            7, //秘术师
            8, //召唤师
            25865, //学者 Broil IV
            7, //双剑师
            7, //忍者
            8, //机工士
            7, //暗黑骑士
            25871, //占星术士 Fall Malefic
            7, //武士 
            7, //赤魔法师
            7, //青魔法师
            7, //绝枪战士
            7, //舞者
            7, //Reaper
            24312, //Sage Dosis III
            7, //Viper
            8, //画家
        };

        // <auto-generated: SkillPot>
        public static Dictionary<uint, float> SkillPot = new()
        {
            { 9, 220f }, // Fast Blade
            { 15, 330f }, // Riot Blade
            { 16, 100f }, // Shield Bash
            { 21, 330f }, // Rage of Halone
            { 23, 140f }, // Circle of Scorn
            { 24, 100f }, // Shield Lob
            { 29, 270f }, // Spirits Within
            { 31, 240f }, // Heavy Swing
            { 37, 340f }, // Maim
            { 41, 110f }, // Overpower
            { 42, 500f }, // Storm's Path
            { 44, 55f }, // Vengeance
            { 45, 500f }, // Storm's Eye
            { 46, 150f }, // Tomahawk
            { 49, 330f }, // Inner Beast
            { 51, 160f }, // Steel Cyclone
            { 53, 420f }, // Bootshine
            { 54, 500f }, // True Strike
            { 56, 480f }, // Snap Punch
            { 61, 420f }, // Twin Snakes
            { 62, 120f }, // Arm of the Destroyer
            { 66, 360f }, // Demolish
            { 70, 150f }, // Rockbreaker
            { 74, 320f }, // Dragon Kick
            { 75, 230f }, // True Thrust
            { 78, 280f }, // Vorpal Thrust
            { 84, 380f }, // Full Thrust
            { 86, 110f }, // Doom Spike
            { 87, 250f }, // Disembowel
            { 88, 260f }, // Chaos Thrust
            { 90, 350f }, // Piercing Talon
            { 92, 320f }, // Jump
            { 96, 500f }, // Dragonfire Dive
            { 97, 160f }, // Heavy Shot
            { 98, 200f }, // Straight Shot
            { 100, 100f }, // Venomous Bite
            { 106, 110f }, // Quick Nock
            { 107, 300f }, // Barrage
            { 110, 130f }, // Bloodletter
            { 113, 60f }, // Windbite
            { 117, 100f }, // Rain of Death
            { 119, 140f }, // Stone
            { 121, 50f }, // Aero
            { 127, 190f }, // Stone II
            { 132, 50f }, // Aero II
            { 139, 140f }, // Holy
            { 141, 180f }, // Fire
            { 142, 180f }, // Blizzard
            { 144, 100f }, // Thunder
            { 147, 80f }, // Fire II
            { 152, 290f }, // Fire III
            { 153, 120f }, // Thunder III
            { 154, 290f }, // Blizzard III
            { 156, 100f }, // Scathe
            { 159, 120f }, // Freeze
            { 162, 240f }, // Flare
            { 163, 240f }, // Ruin
            { 167, 100f }, // Energy Drain
            { 172, 270f }, // Ruin II
            { 181, 340f }, // Fester
            { 2240, 300f }, // Spinning Edge
            { 2242, 400f }, // Gust Slash
            { 2246, 200f }, // Assassinate
            { 2247, 200f }, // Throwing Dagger
            { 2248, 150f }, // Mug
            { 2254, 100f }, // Death Blossom
            { 2255, 460f }, // Aeolian Edge
            { 2258, 300f }, // Trick Attack
            { 2864, 75f }, // Rook Autoturret
            { 2866, 140f }, // Split Shot
            { 2868, 210f }, // Slug Shot
            { 2870, 110f }, // Spread Shot
            { 2872, 240f }, // Hot Shot
            { 2873, 270f }, // Clean Shot
            { 2874, 130f }, // Gauss Round
            { 2878, 240f }, // Wildfire
            { 2890, 130f }, // Ricochet
            { 3538, 700f }, // Goring Blade
            { 3539, 460f }, // Royal Authority
            { 3547, 400f }, // the Forbidden Chakra
            { 3549, 580f }, // Fell Cleave
            { 3550, 180f }, // Decimate
            { 3554, 340f }, // Fang and Claw
            { 3555, 280f }, // Geirskogul
            { 3556, 340f }, // Wheeling Thrust
            { 3558, 260f }, // Empyreal Arrow
            { 3560, 100f }, // Iron Jaws
            { 3562, 400f }, // Sidewinder
            { 3563, 500f }, // Armor Crush
            { 3566, 180f }, // Dream Within a Dream
            { 3568, 220f }, // Stone III
            { 3571, 400f }, // Assize
            { 3576, 300f }, // Blizzard IV
            { 3577, 300f }, // Fire IV
            { 3578, 150f }, // Painflare
            { 3579, 400f }, // Ruin III
            { 3584, 220f }, // Broil
            { 3596, 150f }, // Malefic
            { 3598, 160f }, // Malefic II
            { 3614, 900f }, // Essential Dignity
            { 3615, 120f }, // Gravity
            { 3617, 300f }, // Hard Slash
            { 3621, 120f }, // Unleash
            { 3623, 380f }, // Syphon Strike
            { 3624, 150f }, // Unmend
            { 3632, 480f }, // Souleater
            { 3639, 50f }, // Salted Earth
            { 3641, 240f }, // Abyssal Drain
            { 3643, 540f }, // Carve and Spit
            { 7381, 120f }, // Total Eclipse
            { 7383, 320f }, // Requiescat
            { 7384, 700f }, // Holy Spirit
            { 7386, 150f }, // Onslaught
            { 7387, 420f }, // Upheaval
            { 7391, 240f }, // Quietus
            { 7392, 600f }, // Bloodspiller
            { 7397, 120f }, // Sonic Thrust
            { 7399, 380f }, // Mirage Dive
            { 7400, 720f }, // Nastrond
            { 7401, 250f }, // Hellfrog Medium
            { 7402, 550f }, // Bhavacakra
            { 7404, 50f }, // Pitch Perfect
            { 7406, 150f }, // Caustic Bite
            { 7407, 100f }, // Stormbite
            { 7409, 280f }, // Refulgent Arrow
            { 7410, 200f }, // Heat Blast
            { 7411, 220f }, // Heated Split Shot
            { 7412, 320f }, // Heated Slug Shot
            { 7413, 420f }, // Heated Clean Shot
            { 7415, 320f }, // Rook Overdrive
            { 7420, 80f }, // Thunder IV
            { 7422, 600f }, // Foul
            { 7426, 520f }, // Ruin IV
            { 7429, 300f }, // Enkindle Bahamut
            { 7431, 260f }, // Stone IV
            { 7432, 500f }, // Divine Benison
            { 7435, 240f }, // Broil II
            { 7442, 190f }, // Malefic III
            { 7447, 60f }, // Thunder II
            { 7477, 200f }, // Hakaze
            { 7478, 300f }, // Jinpu
            { 7479, 300f }, // Shifu
            { 7480, 340f }, // Yukikaze
            { 7481, 420f }, // Gekko
            { 7482, 420f }, // Kasha
            { 7483, 90f }, // Fuga
            { 7484, 120f }, // Mangetsu
            { 7485, 120f }, // Oka
            { 7486, 270f }, // Enpi
            { 7490, 250f }, // Hissatsu: Shinten
            { 7491, 100f }, // Hissatsu: Kyuten
            { 7492, 100f }, // Hissatsu: Gyoten
            { 7493, 100f }, // Hissatsu: Yaten
            { 7496, 400f }, // Hissatsu: Guren
            { 7503, 170f }, // Jolt
            { 7504, 130f }, // Riposte
            { 7505, 360f }, // Verthunder
            { 7506, 130f }, // Corps-a-corps
            { 7507, 360f }, // Veraero
            { 7509, 170f }, // Scatter
            { 7510, 380f }, // Verfire
            { 7511, 380f }, // Verstone
            { 7512, 150f }, // Zwerchhau
            { 7513, 60f }, // Moulinet
            { 7515, 180f }, // Displacement
            { 7516, 230f }, // Redoublement
            { 7517, 480f }, // Fleche
            { 7518, 50f }, // Acceleration
            { 7519, 420f }, // Contre Sixte
            { 7524, 280f }, // Jolt II
            { 7562, 55f }, // Lucid Dreaming
            { 11384, 200f }, // 4-tonze Weight
            { 11385, 200f }, // Water Cannon
            { 11386, 50f }, // Song of Torment
            { 11387, 220f }, // High Voltage
            { 11388, 20f }, // Bad Breath
            { 11389, 150f }, // Flying Frenzy
            { 11390, 140f }, // Aqua Breath
            { 11391, 220f }, // Plaincracker
            { 11393, 50f }, // Bristle
            { 11394, 200f }, // Mind Blast
            { 11395, 50f }, // Blood Drain
            { 11396, 200f }, // Bomb Toss
            { 11398, 600f }, // Drill Cannons
            { 11399, 220f }, // the Look
            { 11400, 450f }, // Sharpened Knife
            { 11402, 220f }, // Flame Thrower
            { 11404, 220f }, // Glower
            { 11407, 2f }, // Final Sting
            { 11408, 800f }, // Self-destruct
            { 11418, 40f }, // Ice Spikes
            { 11419, 220f }, // the Ram's Voice
            { 11420, 400f }, // the Dragon's Voice
            { 11422, 200f }, // Ink Jet
            { 11423, 10f }, // Flying Sardine
            { 11425, 200f }, // Fire Angon
            { 11426, 220f }, // Feather Rain
            { 11427, 300f }, // Eruption
            { 11428, 400f }, // Mountain Buster
            { 11429, 400f }, // Shock Strike
            { 11430, 350f }, // Glass Dance
            { 11431, 50f }, // Veil of the Whorl
            { 15989, 220f }, // Cascade
            { 15990, 280f }, // Fountain
            { 15991, 280f }, // Reverse Cascade
            { 15992, 340f }, // Fountainfall
            { 15993, 120f }, // Windmill
            { 15994, 160f }, // Bladeshower
            { 15995, 160f }, // Rising Windmill
            { 15996, 200f }, // Bloodshower
            { 16005, 540f }, // Saber Dance
            { 16007, 180f }, // Fan Dance
            { 16008, 100f }, // Fan Dance II
            { 16009, 220f }, // Fan Dance III
            { 16137, 300f }, // Keen Edge
            { 16139, 380f }, // Brutal Shell
            { 16141, 100f }, // Demon Slice
            { 16143, 150f }, // Lightning Shot
            { 16144, 250f }, // Danger Zone
            { 16145, 460f }, // Solid Barrel
            { 16146, 440f }, // Gnashing Fang
            { 16149, 160f }, // Demon Slaughter
            { 16153, 340f }, // Sonic Break
            { 16159, 150f }, // Bow Shock
            { 16162, 420f }, // Burst Strike
            { 16163, 300f }, // Fated Circle
            { 16165, 800f }, // Blasting Zone
            { 16457, 220f }, // Prominence
            { 16458, 350f }, // Holy Circle
            { 16459, 500f }, // Confiteor
            { 16460, 460f }, // Atonement
            { 16461, 150f }, // Intervene
            { 16462, 140f }, // Mythril Tempest
            { 16464, 400f }, // Nascent Flash
            { 16466, 100f }, // Flood of Darkness
            { 16467, 300f }, // Edge of Darkness
            { 16468, 160f }, // Stalwart Soul
            { 16469, 160f }, // Flood of Shadow
            { 16470, 460f }, // Edge of Shadow
            { 16472, 620f }, // Living Shadow
            { 16473, 140f }, // Four-point Fury
            { 16474, 160f }, // Enlightenment
            { 16476, 780f }, // Six-sided Star
            { 16477, 150f }, // Coerthan Torment
            { 16478, 400f }, // High Jump
            { 16480, 840f }, // Stardiver
            { 16481, 800f }, // Hissatsu: Senei
            { 16487, 640f }, // Shoha
            { 16488, 120f }, // Hakke Mujinsatsu
            { 16489, 850f }, // Meisui
            { 16493, 160f }, // Bunshin
            { 16494, 300f }, // Shadowbite
            { 16495, 220f }, // Burst Shot
            { 16496, 700f }, // Apex Arrow
            { 16497, 180f }, // Auto Crossbow
            { 16498, 660f }, // Drill
            { 16499, 50f }, // Bioblaster
            { 16500, 660f }, // Air Anchor
            { 16502, 680f }, // Queen Overdrive
            { 16505, 350f }, // Despair
            { 16507, 890f }, // Xenoglossy
            { 16508, 200f }, // Energy Drain
            { 16510, 100f }, // Energy Siphon
            { 16511, 100f }, // Outburst
            { 16524, 140f }, // Verthunder II
            { 16525, 140f }, // Veraero II
            { 16526, 260f }, // Impact
            { 16527, 180f }, // Engagement
            { 16529, 100f }, // Reprise
            { 16532, 85f }, // Dia
            { 16533, 290f }, // Glare
            { 16535, 400f }, // Afflatus Misery
            { 16539, 165f }, // Art of War
            { 16541, 255f }, // Broil III
            { 16555, 230f }, // Malefic IV
            { 17209, 20f }, // Hypercharge
            { 17869, 150f }, // Ruin
            { 17870, 220f }, // Ruin II
            { 18295, 220f }, // Alpine Draft
            { 18296, 220f }, // Protean Wave
            { 18297, 220f }, // Northerlies
            { 18298, 220f }, // Electrogenesis
            { 18299, 220f }, // Kaltstrahl
            { 18300, 220f }, // Abyssal Transfixion
            { 18304, 100f }, // Gobskin
            { 18305, 250f }, // Magic Hammer
            { 18308, 210f }, // Sonic Boom
            { 18309, 80f }, // Whistle
            { 18310, 400f }, // White Knight's Tour
            { 18311, 400f }, // Black Knight's Tour
            { 18314, 220f }, // Perpetual Ray
            { 18316, 500f }, // Revenge Blast
            { 18319, 220f }, // Reflux
            { 18320, 250f }, // Devour
            { 18323, 200f }, // Surpanakha
            { 18324, 300f }, // Quasar
            { 18325, 300f }, // J Kick
            { 23264, 150f }, // Triple Trident
            { 23265, 100f }, // Tingle
            { 23266, 220f }, // Tatami-gaeshi
            { 23267, 400f }, // Cold Fog
            { 23269, 140f }, // Stotram
            { 23270, 500f }, // Saintly Beam
            { 23271, 220f }, // Feculent Flood
            { 23273, 500f }, // Chelonian Gate
            { 23275, 400f }, // The Rose of Destruction
            { 23278, 220f }, // Blaze
            { 23279, 220f }, // Mustard Bomb
            { 23281, 50f }, // Aetherial Spark
            { 23282, 220f }, // Hydro Pull
            { 23283, 200f }, // Malediction of Water
            { 23284, 300f }, // Choco Meteor
            { 23285, 100f }, // Matra Magic
            { 23286, 400f }, // Peripheral Synthesis
            { 23287, 600f }, // Both Ends
            { 23288, 600f }, // Phantom Flurry
            { 23290, 400f }, // Nightbloom
            { 23416, 140f }, // Stotram
            { 24283, 300f }, // Dosis
            { 24289, 400f }, // Phlegma
            { 24297, 160f }, // Dyskrasia
            { 24304, 300f }, // Toxikon
            { 24305, 300f }, // Haima
            { 24306, 320f }, // Dosis II
            { 24307, 490f }, // Phlegma II
            { 24311, 200f }, // Panhaima
            { 24312, 380f }, // Dosis III
            { 24313, 600f }, // Phlegma III
            { 24315, 170f }, // Dyskrasia II
            { 24316, 380f }, // Toxikon II
            { 24318, 380f }, // Pneuma
            { 24373, 420f }, // Slice
            { 24374, 500f }, // Waxing Slice
            { 24375, 600f }, // Infernal Slice
            { 24376, 140f }, // Spinning Scythe
            { 24377, 180f }, // Nightmare Scythe
            { 24378, 300f }, // Shadow of Death
            { 24379, 100f }, // Whorl of Death
            { 24380, 520f }, // Soul Slice
            { 24381, 180f }, // Soul Scythe
            { 24382, 620f }, // Gibbet
            { 24383, 620f }, // Gallows
            { 24384, 200f }, // Guillotine
            { 24385, 720f }, // Plentiful Harvest
            { 24386, 300f }, // Harpe
            { 24389, 340f }, // Blood Stalk
            { 24392, 140f }, // Grim Swathe
            { 24393, 520f }, // Gluttony
            { 24398, 100f }, // Communio
            { 25747, 450f }, // Expiacion
            { 25751, 400f }, // Bloodwhetting
            { 25752, 150f }, // Orogeny
            { 25753, 700f }, // Primal Rend
            { 25755, 500f }, // Salt and Darkness
            { 25757, 600f }, // Shadowbringer
            { 25760, 15f }, // Double Down
            { 25761, 180f }, // Steel Peak
            { 25763, 100f }, // Howling Fist
            { 25767, 120f }, // Shadow of the Destroyer
            { 25771, 460f }, // Heavens' Thrust
            { 25772, 340f }, // Chaotic Spring
            { 25773, 440f }, // Wyrmwind Thrust
            { 25774, 700f }, // Phantom Kamaitachi
            { 25777, 700f }, // Forked Raiju
            { 25778, 700f }, // Fleeting Raiju
            { 25780, 100f }, // Fuko
            { 25781, 40f }, // Ogi Namikiri
            { 25783, 140f }, // Ladonsbite
            { 25786, 130f }, // Scattergun
            { 25788, 660f }, // Chain Saw
            { 25791, 460f }, // Fan Dance IV
            { 25792, 600f }, // Starfall Dance
            { 25793, 80f }, // Blizzard II
            { 25794, 100f }, // High Fire II
            { 25795, 100f }, // High Blizzard II
            { 25800, 50f }, // Aethercharge
            { 25802, 400f }, // Summon Ruby
            { 25803, 400f }, // Summon Topaz
            { 25804, 400f }, // Summon Emerald
            { 25805, 600f }, // Summon Ifrit
            { 25806, 600f }, // Summon Titan
            { 25807, 600f }, // Summon Garuda
            { 25826, 120f }, // Tri-disaster
            { 25838, 800f }, // Summon Ifrit II
            { 25839, 800f }, // Summon Titan II
            { 25840, 800f }, // Summon Garuda II
            { 25855, 440f }, // Verthunder III
            { 25856, 440f }, // Veraero III
            { 25859, 350f }, // Glare III
            { 25860, 150f }, // Holy III
            { 25865, 320f }, // Broil IV
            { 25866, 180f }, // Art of War II
            { 25871, 270f }, // Fall Malefic
            { 25872, 140f }, // Gravity II
            { 25874, 270f }, // Macrocosmos
            { 34563, 220f }, // Goblin Punch
            { 34564, 110f }, // Right Round
            { 34565, 100f }, // Schiltron
            { 34568, 500f }, // Wild Rage
            { 34569, 100f }, // Peat Pelt
            { 34570, 220f }, // Deep Clean
            { 34571, 220f }, // Ruby Dynamics
            { 34572, 100f }, // Divination Rune
            { 34574, 440f }, // Conviction Marcato
            { 34576, 400f }, // Winged Reprobation
            { 34577, 220f }, // Laser Eye
            { 34578, 250f }, // Candy Cane
            { 34580, 500f }, // Sea Shanty
            { 34582, 800f }, // Being Mortal
            { 34606, 300f }, // Steel Fangs
            { 34607, 300f }, // Reaving Fangs
            { 34614, 140f }, // Steel Maw
            { 34615, 140f }, // Reaving Maw
            { 34620, 500f }, // Vicewinder
            { 34621, 570f }, // Hunter's Coil
            { 34622, 570f }, // Swiftskin's Coil
            { 34623, 250f }, // Vicepit
            { 34624, 300f }, // Hunter's Den
            { 34625, 300f }, // Swiftskin's Den
            { 34626, 750f }, // Reawaken
            { 34632, 200f }, // Writhing Snap
            { 34633, 680f }, // Uncoiled Fury
            { 34650, 490f }, // Fire in Red
            { 34653, 860f }, // Blizzard in Cyan
            { 34656, 180f }, // Fire II in Red
            { 34659, 360f }, // Blizzard II in Cyan
            { 34662, 570f }, // Holy in White
            { 34663, 940f }, // Comet in Black
            { 34676, 70f }, // Mog of the Ages
            { 34678, 560f }, // Hammer Stamp
            { 34681, 100f }, // Star Prism
            { 34688, 85f }, // Rainbow Drip
            { 36920, 1f }, // Guardian
            { 36921, 580f }, // Imperator
            { 36923, 55f }, // Damnation
            { 36932, 25f }, // Disesteem
            { 36937, 800f }, // Reign of Beasts
            { 36944, 500f }, // Earth's Reply
            { 36945, 460f }, // Leaping Opo
            { 36946, 540f }, // Rising Raptor
            { 36947, 520f }, // Pouncing Coeurl
            { 36949, 40f }, // Wind's Reply
            { 36950, 400f }, // Fire's Reply
            { 36952, 460f }, // Drakesbane
            { 36953, 550f }, // Rise of the Dragon
            { 36954, 340f }, // Lance Barrage
            { 36955, 300f }, // Spiral Blow
            { 36956, 40f }, // Starcross
            { 36957, 400f }, // Dokumori
            { 36958, 700f }, // Kunai's Bane
            { 36963, 240f }, // Gyofu
            { 36964, 940f }, // Zanshin
            { 36974, 220f }, // Wide Volley
            { 36975, 180f }, // Heartbreak Shot
            { 36976, 640f }, // Resonant Arrow
            { 36977, 50f }, // Radiant Encore
            { 36978, 240f }, // Blazing Shot
            { 36979, 180f }, // Double Check
            { 36980, 180f }, // Checkmate
            { 36982, 900f }, // Full Metal Field
            { 36983, 540f }, // Last Dance
            { 36986, 150f }, // High Thunder
            { 36987, 100f }, // High Thunder II
            { 36989, 500f }, // Flare Star
            { 36990, 460f }, // Necrotize
            { 36991, 600f }, // Searing Flash
            { 37004, 360f }, // Jolt III
            { 37005, 950f }, // Vice of Thorns
            { 37007, 200f }, // Prefulgence
            { 37009, 640f }, // Glare IV
            { 37011, 400f }, // Divine Caress
            { 37029, 860f }, // Oracle
            { 37033, 600f }, // Psyche
        };
// </auto-generated: SkillPot>

        public static Dictionary<uint, float> SkillPot94 = new()
        {
            { 7, 90f }, //?
            { 8, 80f }, //?

            { 3577, 300f * 1.8f }, //火4 @ 3层火

            // { 3568, 230 }, //垒石
            // { 7431, 270 }, //崩石
            // { 16533, 290 }, //闪耀
            { 25859, 310 }, //闪耀3 310

            // { 3584, 220 }, //气炎法
            // { 7435, 240 }, //魔炎法
            // { 16541, 255 }, //死炎法
            { 25865, 295 }, //炎法4 295

            // { 3598, 160 }, //灾星
            // { 7442, 190 }, //祸星
            // { 16555, 230 }, //煞星
            { 25871, 250 }, //落星 250

            // { 24283, 300 }, //Dosis
            // { 24306, 320 }, //Dosis2
            { 24312, 330 }, //Dosis3 330
            { 24315, 170 }, //Dyskrasia II
        };

        public static Dictionary<uint, uint> BuffToAction = new()
        {
            { 749, 3639 }, //腐秽大地
            { 501, 2270 }, //土遁之术
            { 861, 2878 }, //野火
            { 2706, 25837 }, //风宝宝
            { 1869, 25837 }, //小风宝宝
            { 1205, 7418 },//FlameThrower
            
        };

        // <auto-generated: DotPot>
        public static Dictionary<uint, uint> DotPot = new()
        {
            { 18, 20 },
            { 118, 40 },
            { 124, 15 },
            { 129, 20 },
            { 143, 30 },
            { 144, 50 },
            { 161, 45 },
            { 162, 30 },
            { 163, 50 },
            { 179, 20 },
            { 189, 40 },
            { 248, 30 },
            { 269, 40 },
            { 272, 20 },
            { 273, 50 },
            { 749, 50 },
            { 838, 50 },
            { 843, 60 },
            { 1200, 20 },
            { 1201, 25 },
            { 1205, 120 },
            { 1210, 35 },
            { 1228, 50 },
            { 1312, 40 },
            { 1321, 20 },
            { 1458, 120 },
            { 1837, 120 },
            { 1838, 60 },
            { 1866, 50 },
            { 1871, 85 },
            { 1881, 70 },
            { 1895, 85 },
            { 2136, 40 },
            { 2502, 200 },
            { 2614, 40 },
            { 2615, 60 },
            { 2616, 85 },
            { 2719, 45 },
            { 3079, 80 },
            { 3227, 30 },
            { 3636, 10 },
            { 3644, 140 },
            { 3712, 120 },
            { 3871, 60 },
            { 3872, 40 },
            { 3883, 140 },
            { 3897, 40 },
            { 4007, 50 },
        };
// </auto-generated: DotPot>
                
        public static Dictionary<uint, uint> DotPot94 = new()
        {

            { 248, 30 }, //厄运流转

            { 1837, 60 }, //音速破
            { 1838, 60 }, //弓形冲波


            //{ 144, 60 }, //烈风
            { 1871, 65 }, //天辉 65

            //{ 17865, 40 }, //猛毒菌
            { 1895, 70 }, //蛊毒法 70
            { 3883, 140 }, //Baneful Impaction

            //{ 843, 50 }, //炽灼
            { 1881, 55 }, //焚灼 55

            //{ 2614, 40 }, //Eukrasian Dosis(低等级不准)
            //{ 2615, 60 }, //Eukrasian Dosis2
            { 2616, 75 }, //Eukrasian Dosis3
            { 3897, 40 },//Eukrasian Dyskrasia


            //{ 118, 40 }, //樱花怒放
            { 2719 , 45 },//樱花缭乱

            { 1228, 45 }, //彼岸花 45


            //{ 129, 20 }, //风蚀箭
            { 1201, 25 }, //狂风蚀箭
            //{ 124, 15 }, //毒咬箭
            { 1200, 20 }, //烈毒咬箭

            { 1866, 50 },//喷毒


            //{ 161, 35 }, //闪雷 1
            { 163, 45 }, //暴雷 3
            //{ 162, 15 }, //震雷 2
            { 1210, 35 }, //霹雷 AOE 4
            { 3871, 55 }, //High Thunder
            { 3872, 40 }, //High Thunder2


        };
    }

    internal enum Job : uint
    {
        ADV = 0,
        GLA = 1,
        PGL = 2,
        MRD = 3,
        LNC = 4,
        ARC = 5,
        CNJ = 6,
        THM = 7,
        CRP = 8,
        BSM = 9,
        ARM = 10,
        GSM = 11,
        LTW = 12,
        WVR = 13,
        ALC = 14,
        CUL = 15,
        MIN = 16,
        BTN = 17,
        FSH = 18,
        PLD = 19,
        MNK = 20,
        WAR = 21,
        DRG = 22,
        BRD = 23,
        WHM = 24,
        BLM = 25,
        ACN = 26,
        SMN = 27,
        SCH = 28,
        ROG = 29,
        NIN = 30,
        MCH = 31,
        DRK = 32,
        AST = 33,
        SAM = 34,
        RDM = 35,
        BLU = 36,
        GNB = 37,

        DNC = 38,
        RPR = 39,
        SGE = 40,
        VPR = 41,
        PCT = 42
    }
}
